# Generated by Django 6.1.1 on 2026-09-16 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
